### ISSUE TITLE
Problems with the mapeditor

### ISSUE THREAD

**Issue by bluuue** [DDRace/teeworlds#180]
hello,
At the moment i make a map with the DDRace.exe  mapeditor (1.12a)
It is very big (500x500 Tiles). Today I added a Tileset to my map and then i made some Teleports.
After that i had the problem that the gui of the mapeditor didnt react anymore, especially when i zoom out.
Is there still a fix for that or could you make one? I can send you the map if you want to test it.
I also sent the map to a friend of me and told him to load the map in his ddrace mapeditor and he reported me
that he hasnt such huge problems, but the map only lags if he zoomes out completely. But he said that the gui
doesnt stop reacting on his computer.

And another problem which i have is that when i use the shift key to make more then one tile in the map, very often
it happens that the tiles doesnt appear on the places where i selected them.

mfg ßlµe

**Comment by eeeee** [comment]
Do you experience same problems when opening the map in teeworlds.exe mapeditor?

**Comment by bluuue** [comment]
no when i try to load the map with the normal mapeditor the program gets closed completely because im using a tele layer and speedup

**Comment by bluuue** [comment]
btw its the newest 1.12a version which i used.  I tried it with the oldest 1.12a now, but i have the same problem.
my computer:  i7 920,  6gb ram, win xp

**Comment by eeeee** [comment]
you should post your map to some file uploading service, somebody will check it out then

**Comment by bluuue** [comment]
https://rapidshare.com/#!download|758p1|1702300381|LowPossibility3.map|604|R~3D291F666272C01B522A2F8A037E1693|0|0

here the map. i hope that it worked

**Comment by Tsin** [comment]
i just checked the map and it works fine on 0.96a  total zoom out no problems  (ofcourse the game gets less fps but still works) and total zoom in also fine 

wont test on 1.12 couse i dont like that version =P and its entities :P

**Comment by bluuue** [comment]
yeah it works fine on 0.96a, thanks a lot

**Comment by Learath2** [comment]
Whats the problem with that :/

**Comment by walter-P2Z** [comment]
Hi,

I wanted to signals this editor problem. I actually can't map with the latest windows build because the editors make some weird stuffs that happens randomly : 
- The GUI totaly disappears. (see : http://dl.free.fr/oBhexQMT6)
- The GUI partialy disappears. (see : http://dl.free.fr/ep77QZMlw)
- Mouse and keyboard doesn't works sometimes.

An example of map that makes the editor bugs can be downloaded here :  http://dl.free.fr/k7CEJqY84

I tested some DDrace builds from DDrace.info and i conclued that those problems probably appears with the version 1.12a. Unfortunatly i could not try on linux for now, but i'll try to test it too.

I have thoses problems on those builds:  

```
    Date : 03-24-2012 08:20:54
    Version : 1.12a
    Hash : 9ed9dbb9
    OS : Windows 7

    Date : 03-20-2012 13:25:26
    Version : 1.12a
    Hash : b560e313
    OS : Windows 7

    Date : 02-07-2012 12:51:55
    Version : 1.12a
    Hash : 7bd9a687
    OS : Windows 7
```

But not on this build:

```
    Date : 11-16-2011 13:24:35
    Version : 1.096a 
    Hash : 1837c76a
    OS : Windows 7
```

I hope those informations will help you to fix those problems :)

**Comment by Learath2** [comment]
If i could reproduce it. Mapped for a good hr or two using everything I see in the editor just to make it reproduce it. No success. Tried it with your maps too it just wouldn't reproduce it. Damn comment and close button...

**Comment by walter-P2Z** [comment]
Hi,

I'm happy to see that this issue is still opened ;D
i made a little video where i present a rapid way to make the editor bug : http://dl.free.fr/tKBn8lXvg

Steps are :
- Open the map
- zoom out 5/6 times
- move with Ctrl+mouse (or middle bouton)

Video made on this build :

```
Date : 03-24-2012 08:20:54
Version : 1.12a
Hash : 9ed9dbb9
OS : Windows 7
```

Information about my system :

```
Motherboard : ASUS P5Q3 Deluxe (Chipset P45)
CPU : Intel(R) Core(TM)2 Duo CPU E8500 (3.16 GHz)
Memory : 6GB DDR3
GraphicCard : ATI Radeon 4870 (GPU RV770)
OS : Windows Seven Professional SP1 (64bits)
```

I finally succed to test on Linux and the result is exactly the same !

```
OS : Ubuntu 12.04.1 desktop i386
VM : VirtualBox v4.2.0 r80737
```

Tested builds :

```
Date : 03-24-2012 08:20:54
Version : 1.14a
Hash : 9ed9dbb9

Date :04-25-2012 14:13:02
Version : 1.12a
Hash : 5c2d829
```

EDIT : I noticed that the graphical bugs doesn't appears if the game group is hide. But the mouse problem is still there (especially scrolling)

**Comment by AdVetter** [comment]
The scrolling/mouse problem should be fixed already 8372849cbafb02a58fcf8aa7c706cad5c5f16731

**Comment by walter-P2Z** [comment]
That's great XXLTomate, I didn't see this !

The GUI problem doesn't appear neither in Vanilla Client. But it doesn't allow to make DDrace features. 

I try to search what triggers those problems and it looks to be the graphical numbers : tiles info, tele numbers, switch number/delay or speedup strenght. Apparently it doesn't come from the map because it also bugs with ctf5 when tiles info is ON.

Hope it will help you guys.

**Comment by ghost** [comment]
This is indeed a problem with the threaded graphic engine:
U can avoid this by batching stuff and reduce the number of drawcalls. I did a pull request to the main repo for the Show Info stuff, which reduces the number of drawcalls quite much. It doesnt fix the actual 'problem'. (But atm with good batching the gui problem shouldnt appear in 99% of cases (: )
